import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import { twMerge } from "tailwind-merge";

const fonts = Prompt({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Clodron Saas || Startup Landing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          fonts.className,
          "bg-neutral-950 text-white antialiased",
        )}>
        {children}
      </body>
    </html>
  );
}
